language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - '14'
dist: xenial
sudo: false
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm i
  - npm i -g codecov@3.7.0
script:
  - npm run lint
  - npm test
  - codecov
