language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '16'
dist: xenial
sudo: false
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm i -g codecov@3.7.0
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn test
  - codecov
